name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Get the current date
      id: date
      run: echo "::set-output name=date::$(date +%s)"
    
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: negin513/neon-app:${{ steps.date.outputs.date }}

      #run: docker build . --file Dockerfile --no-cache -tag negin513/neon-app:$(date +%s)
